plugins {
    alias(libs.plugins.android.application)
    id 'realm-android'
}

android {
    namespace 'com.example.merchmob'
    compileSdk {
        version = release(36) {
            minorApiLevel = 1
        }
    }

    defaultConfig {
        applicationId "com.example.merchmob"
        minSdk 26
        targetSdk 29
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            optimization {
                enable false
            }
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }

}

dependencies {
    // CAMERA DEPENDENCIES
    implementation files('libs/Android-Image-Cropper-release.aar')
    implementation "androidx.exifinterface:exifinterface:1.4.2"

    // KARUMI DEPENDENCES
    implementation 'com.squareup.picasso:picasso:2.71828'

    // PERMISSIONS
    implementation 'com.karumi:dexter:6.2.3'

    implementation libs.recyclerview
    implementation files('libs/realmadapter4.0.0.jar')

    implementation libs.activity.ktx
    implementation libs.appcompat
    implementation libs.constraintlayout
    implementation libs.material
    implementation libs.navigation.fragment
    implementation libs.navigation.ui
    implementation libs.recyclerview

    testImplementation libs.junit
    androidTestImplementation libs.espresso.core
    androidTestImplementation libs.ext.junit
}